name: 'ROS2 Build tool'
description: 'Target description is Humble'

intputs:
  display_message:
    description: 'Out some random message'
    required: false
    default: 'I am run to edge of the world to build this environment'
  image:
    description: 'Image'
    required: true
    default: prachandabhanu/build_env:ros2-humble-kuka
  options:
    description: 'Options'
    required: false
  run:
    description: 'Run command in container'
    required: false
  shell:
    description: 'Use a specific shell'
    required: false
    default: bash

# outputs:
#   ros-workspace-directory-name:
#     description: |
#       outputing somthing here

runs:
  using: 'docker'
  image: 'Dockerfile'